spring:
    application:
        name: API-GATEWAY
    jmx:
        default-domain: gateway
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB

server:
    port: 8090
    servlet:
        context-path: /api

eureka:
    instance:
        prefer-ip-address: true
        instance-id: (${random.int(99)}) - ${spring.application.name} - v${application-version}
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8091/eureka-server/eureka}

zuul:
    ignored-services: '*'
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    sensitiveHeaders: Cookie,Set-Cookie 
    routes:
        mv-service:
            path: /mv/**
            service-id: API-MV
            strip-prefix: false
        gsi-service:
            sensitiveHeaders:
            path: /gsi/**
            service-id: API-GSI
            strip-prefix: false
        mensageria-service:
            path: /mensageria/**
            service-id: API-MENSAGERIA
            strip-prefix: false
        sentinela-service:
            path: /sentinela/**
            service-id: API-SENTINELA
            strip-prefix: false
        guardian-service:
            path: /guardian/**
            service-id: API-GUARDIAN
            strip-prefix: false
        biofast-service:
            path: /biofast/**
            service-id: API-BIOFAST
            strip-prefix: false
        api01-service:
            path: /api01/**
            service-id: API-01
            strip-prefix: false
        api02-service:
            path: /api02/**
            service-id: API-02
            strip-prefix: false
        sms-mv-service:
            path: /smsmv/**
            service-id: API-SMS-MV
            strip-prefix: false
        elegibilidade-service:
            path: /elegibilidade/**
            service-id: API-ELEGIBILIDADE
            strip-prefix: false
    host:
        socket-timeout-millis: 30000
        connect-timeout-millis: 30000
        
ribbon:
    ReadTimeout: 60000
    eager-load:
        enabled: true #resolve timeout na primeira chamada

app.version: 1.0.0-SNAPSHOT